### ISSUE TITLE
Missing 'amountToApprove' int types definition for TransactionData 

### ISSUE THREAD

**Issue by Krumil** [brian-knows/brian-sdk#1]
## Description

The current type definitions in the Brian AI SDK are missing the `amountToApprove` property in the `TransactionData` interface. This property is present in the actual API response but not reflected in the TypeScript definitions, causing type errors when trying to access this field.

## Current Behavior

When using the `transact` method of the BrianSDK, the response includes an `amountToApprove` field in the `data` object of each transaction result. However, the TypeScript definitions do not include this field, leading to type errors when attempting to access it.

## Expected Behavior

The `TransactionData` interface in the SDK's type definitions should include the `amountToApprove` property to match the actual API response structure.

**Comment by PaoloRollo** [comment]
Hey @Krumil, thanks for the issue. It will be addressed in the next release of the SDK and API, where this field will no longer be available in the result.
